### ISSUE TITLE
Connect Front End with Back End

### ISSUE THREAD

**Issue by mlpollar** [erozhon/CSC308-Rideshare#34]

**Comment by mlpollar** [comment]
#34

**Comment by garrettlew** [comment]
1. Doing the front end for submitting the posts
2. Doing the front end for the post feeds

**Comment by garrettlew** [comment]
Knowledge transfer about backend with frontend
Overlay design rough draft on backend + react

Goal: To have front end page request data from database (django) and have the data displayed in a nice format
#42
