### ISSUE TITLE
Going to profile redirects to alipay

### ISSUE THREAD

**Issue by nauticalmonkey** [erozhon/CSC308-Rideshare#67]
When trying to go to the profile page from the right hand drop down menu goes to alipay
From the main home screen use the drop down menu and select the drop down menu.
Expected behavior: i expect to go to a profile page of CalpolyRides
Ob Behavior: goes to alipay main home screen

**Comment by garrettlew** [comment]
Addressed: e4bca912e32dc48b36f7d02858d017959d5e477f
