### ISSUE TITLE
Log out does not work

### ISSUE THREAD

**Issue by nauticalmonkey** [erozhon/CSC308-Rideshare#68]
when trying to hit the log out button it brings you to a different unrelated site.
Reproduction: using the left hand drop down menu try to log out using the log out menu
Expected Behavior: i expected a profile that i had logged in as to be logged out. i would then expect either a message dictating that i logged out
Observed behavior: it took me to tmall main index site

**Comment by garrettlew** [comment]
Addressed: #84
